import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import { ToastContainer } from 'react-toastify'
import ClientProvider from './store/ClientProvider'
import 'react-toastify/dist/ReactToastify.css'

export const metadata = {
  title: 'Post CRUD App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ClientProvider>{children}</ClientProvider>
        <ToastContainer position="top-center" />
      </body>
    </html>
  )
}
